let snackServings = 3;
let guests = 10;
console.log(snackServings + guests);
console.log(guests - snackServings);
console.log(snackServings - guests);
console.log(snackServings * guests);
console.log(snackServings / guests);
let drinks = 10;
resultOne = snackServings * guests;
console.log(resultOne / drinks);
let monkeys = 15;
let bananas = 9;
console.log(monkeys / bananas);
let monkeyFights = 20;
resultTwo = monkeys + bananas;
console.log(resultTwo * monkeyFights);
monkeys++;
bananas--;
console.log(monkeys);
console.log(bananas);
happiness = monkeys - bananas;
console.log(happiness);
console.log(happiness + monkeyFights);
console.log(resultOne);
console.log(resultTwo);
console.log(resultOne % resultTwo);
